format = """
[░▒▓](#DCD7BA)\
[ 󰣇 ](bg:#DCD7BA fg:#1e3d51)\
[](bg:#7AA89F fg:#DCD7BA)\
$directory\
[](fg:#7AA89F bg:#214359)\
$git_branch\
$git_status\
[](fg:#254a63 bg:#1e3d51)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1e3d51 bg:#193444)\
$time\
[ ](fg:#193444)\
\n$character"""

[directory]
style = "fg:#ece7c8 bg:#7AA89F"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#254a63"
format = '[[ $symbol $branch ](fg:#85b8ae bg:#254a63)]($style)'

[git_status]
style = "bg:#254a63"
format = '[[($all_status$ahead_behind )](fg:#85b8ae bg:#254a63)]($style)'

[nodejs]
symbol = ""
style = "bg:#1e3d51"
format = '[[ $symbol ($version) ](fg:#85b8ae bg:#1e3d51)]($style)'

[rust]
symbol = ""
style = "bg:#1e3d51"
format = '[[ $symbol ($version) ](fg:#85b8ae bg:#1e3d51)]($style)'

[golang]
symbol = ""
style = "bg:#1e3d51"
format = '[[ $symbol ($version) ](fg:#85b8ae bg:#1e3d51)]($style)'

[php]
symbol = ""
style = "bg:#1e3d51"
format = '[[ $symbol ($version) ](fg:#85b8ae bg:#1e3d51)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#193444"
format = '[[  $time ](fg:#85b8ae bg:#193444)]($style)'
