format = """
[░▒▓](#e0def4)\
[ 󰣇 ](bg:#e0def4 fg:#1f1d2e)\
[](bg:#8e75c5 fg:#ffffff)\
$directory\
[](fg:#8e75c5 bg:#26233a)\
$git_branch\
$git_status\
[](fg:#26233a bg:#1f1d2e)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1f1d2e bg:#191724)\
$time\
[ ](fg:#191724)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#8e75c5"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#26233a"
format = '[[ $symbol $branch ](fg:#c4a7e7 bg:#26233a)]($style)'

[git_status]
style = "bg:#26233a"
format = '[[($all_status$ahead_behind )](fg:#c4a7e7 bg:#26233a)]($style)'

[nodejs]
symbol = ""
style = "bg:#1f1d2e"
format = '[[ $symbol ($version) ](fg:#c4a7e7 bg:#1f1d2e)]($style)'

[rust]
symbol = ""
style = "bg:#1f1d2e"
format = '[[ $symbol ($version) ](fg:#c4a7e7 bg:#1f1d2e)]($style)'

[golang]
symbol = ""
style = "bg:#1f1d2e"
format = '[[ $symbol ($version) ](fg:#c4a7e7 bg:#1f1d2e)]($style)'

[php]
symbol = ""
style = "bg:#1f1d2e"
format = '[[ $symbol ($version) ](fg:#c4a7e7 bg:#1f1d2e)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#191724"
format = '[[  $time ](fg:#c4a7e7 bg:#191724)]($style)'
